### ISSUE TITLE
setting UID and GID via env

### ISSUE THREAD

**Issue by Stathogon** [JonasAlfredsson/docker-nginx-certbot#100]
hello,
im using cif storages for my dockers and im currently running into permission problems. would it be possible to set the proper UID and GID via env variables? Sadly im not able to change the permissions on the Host. But after all huge probs with this Projects, i really like it and till now it worked perfekt for me.

**Comment by JonasAlfredsson** [comment]
Hi  Stathogon,

I am not entirely sure what permissions you need changed. Is it the files that are created by certbot or something else?
The parent container creates a custom user with ID 101, which Nginx runs as, but it doesn't look like it supports custom IDs beyond that. So I am not sure it will be very easy to expand this to support more UIDs.

**Comment by JonasAlfredsson** [comment]
Do you want to discuss this further or should I close this issue?

**Comment by JonasAlfredsson** [comment]
Closed due to inactivity.
