### ISSUE TITLE
nginx config should hide the server version by default

### ISSUE THREAD

**Issue by farmergreg** [JonasAlfredsson/docker-nginx-certbot#104]
I think it would be good to add:

server_tokens off;

to the nginx configs

**Comment by JonasAlfredsson** [comment]
Hi farmergreg,

Thank you for your suggestion, but I am not sure it is this image's task to fiddle more than the bare minimum with configuration settings. The reason for this is that I want it to be as close to the original Nginx image as possible, with the exception of automatic certificate creation/renewal. 

An easy solution would be to add a custom configuration file that is loaded [before any other](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/nginx_tips.md#how-nginx-loads-configs), e.g. a file called `00-load_there_first.conf` with any settings you want to apply to all coming configurations.

**Comment by farmergreg** [comment]
Thanks @JonasAlfredsson for the fast response, I'll do that.

**Comment by JonasAlfredsson** [comment]
Are you satisfied with the solution so we can close the issue?

**Comment by farmergreg** [comment]
Thanks for asking, using a custom config that loads first is working well for me.
