### ISSUE TITLE
certbot: error: unrecognized arguments: --dns-route53

### ISSUE THREAD

**Issue by kodeine** [JonasAlfredsson/docker-nginx-certbot#115]
So it seems route53 does not support the argv provided.

https://certbot-dns-route53.readthedocs.io/en/stable/index.html

```
nginx-certbot | certbot: error: unrecognized arguments: --dns-route53-credentials=/etc/letsencrypt/route53.ini
```

**Comment by JonasAlfredsson** [comment]
You are right, this authenticator appears to behave differently than all the others, think this is an easy fix.

**Comment by JonasAlfredsson** [comment]
I implemented something I think will fix it, can you please try out the `:latest` image?

**Comment by JonasAlfredsson** [comment]
Hi,
Have you had time to test this yet? :)
