### ISSUE TITLE
Allow overriding CERTBOT_STAGING_URL and CERTBOT_PRODUCTION_URL

### ISSUE THREAD

**Issue by dthusian** [JonasAlfredsson/docker-nginx-certbot#128]
I have a self-hosted ACME certificate authority set up already, and I want to set up this Docker image to request certificates from it. I would need to change the CERTBOT_STAGING_URL and CERTBOT_PRODUCTION_URL variables inside `run_certbot.sh` as well as supplying the root CA certificate, but this isn't possible without modifying the image.

I would suggest being able to override these variables with environment variables from container creation, as well as a way to bind mount in a custom root CA, maybe inside `/etc/letsencrypt/custom_root_ca.crt` or something similar.

**Comment by JonasAlfredsson** [comment]
Hi dthusian,

This sounds really interesting! 
This is absolutely something we can modify the image to handle, but I would like some more information on what you are running as your own certificate authority, and how you want the root certificate to be incorporated in the image. 
Is it only certbot that needs it, or do other processes need it as well?

**Comment by JonasAlfredsson** [comment]
While the change of how we set the `letsencrypt_url` variable is pretty straight forward, the CA certificate is something I am more unsure of how to best proceed. 
Reading [this](https://stackoverflow.com/a/42292623) it seems like it would be easiest for you to include it as a build step for your own Dockerfile. An alternative to that is then either to write your own [entrypoint](https://tyk.io/docs/frequently-asked-questions/add-custom-certificates-to-docker-images/), or utilize the fact that this image run any shell script found in [`/docker-entrypoint.d/`](https://github.com/nginxinc/docker-nginx/tree/master/entrypoint) to run whatever you want at startup.

**Comment by JonasAlfredsson** [comment]
> Are you suggesting that I construct a new Docker image based on this one with my root CA certificate inside it? That would also be a viable solution.

Yes, I think that would be the easiest and most robust solution for.  Just create a Dockerfile with 

```Dockerfile
FROM jonasal/nginx-certbot:3
ADD your_ca_root.crt /usr/local/share/ca-certificates/foo.crt
RUN chmod 644 /usr/local/share/ca-certificates/foo.crt && update-ca-certificates
```
and you should be good to go.
In regards to be able to change the URL I need to update the scripts to support it. 
I can probably take a look at that in 2 days or so.

**Comment by dthusian** [comment]
Thanks. Once being able to change the URL is implemented I can close this issue.

**Comment by JonasAlfredsson** [comment]
[This](https://github.com/JonasAlfredsson/docker-nginx-certbot/commit/8f813fef9adfc66da7bec08e6c68b821200fb2b2) has now been merged, and is included in the latest v.3.2.0 release. Please try it out and see if it works for you. 

Out of curiosity, is there anywhere I can look to see your step-ca deployment/configuration?

**Comment by dtcooper** [comment]
I'd be curious too know as well!

**Comment by dthusian** [comment]
Thanks for implementing this feature, I'll try it out soon.

Unfortunately, my step-ca deployment is not exposed to the public internet, and the configuration files were trivial, so there's not much to show. I essentially followed the getting started guide on Smallstep's website. https://smallstep.com/docs/step-ca/getting-started

**Comment by JonasAlfredsson** [comment]
Alright, I will check this out in the future then. 
Please update when/if you try out the new solution so we know if it worked or not.
