### ISSUE TITLE
Adding new server_name entries to existing configurations

### ISSUE THREAD

**Issue by Keinkil** [JonasAlfredsson/docker-nginx-certbot#13]
Adding a new server_name entry to the configurations of a running copy of docker-nginx-certbot and restarting to pick up the new configuration and generate the new certificate(s) causes a MissingCommandlineFlag error:

```Run certbot!
Getting certificate for domain website.com on behalf of user user@website.com
Using production environment...
Running certbot... https://acme-v02.api.letsencrypt.org/directory website.com user@website.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 14, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1350, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1230, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 287, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 314, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 266, in _find_lineage_for_domains
    return _handle_subset_cert_request(config, domains, subset_names_cert)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 163, in _handle_subset_cert_request
    force_interactive=True):
  File "/usr/local/lib/python3.7/dist-packages/certbot/display/util.py", line 535, in yesno
    self._interaction_fail(message, cli_flag)
  File "/usr/local/lib/python3.7/dist-packages/certbot/display/util.py", line 465, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry for this setting:
You have an existing certificate that contains a portion of the domains you requested (ref: /etc/letsencrypt/renewal/website.com.conf)
It contains these names: website.com, www.website.com
You requested these names for the new certificate: website.com, www.website.com, test.website.com, test.test.website.com.
Do you want to expand and replace this existing certificate with the new certificate?
(You can set this with the --expand flag)
Please see the logfiles in /var/log/letsencrypt for more details.
Certbot failed for website.com. Check the logs for details.
```

This can be manually avoided via deleting old certificates when you want to refresh, but since this already aims to automate as much as possible, it would be great if this could be handled.
https://certbot.eff.org/docs/using.html#re-creating-and-updating-existing-certificates
Adding the flag --cert-name or --expand
Would probably solve this.

**Comment by JonasAlfredsson** [comment]
Interesting find, and good suggestions as solutions. 
I am not 100% sure how the `--cert-name` flag works, but from the documentation it reads like that one allows both adding ad subtracting domains from the certificates. I will take some time and double check that one as soon as possible.

**Comment by JonasAlfredsson** [comment]
I have added the `--cert-name` flag now, since this seems to solve the problem at hand.
The container is also being built with the "latest" tag, but I will do some additional testing before adding an official version number to this change.

**Comment by JonasAlfredsson** [comment]
Furthermore, there is a problem today where my function checks the last time the certificate file was modified, and will not update it even if more domains are added.

https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/64a92ae229bc254ee477903d357549b7bff0a24b/src/scripts/util.sh#L164-L176

I will look in to that tomorrow, and probably remove that check altogether. 

But this raises another concern that then we need to check so that we only make one certbot run per primary domain. I have a preliminary solution for this, but will not push anything before some more experimentation.
