### ISSUE TITLE
Can't use wildcard certificate for serveral subdomains

### ISSUE THREAD

**Issue by mikuslaw** [JonasAlfredsson/docker-nginx-certbot#130]
Hi,

my usecase is that I want to use a wildcard cert (through route53 if that matters) for several subdomains. I specify several conf files with different server_name set (differs only in subdomain) and one with server_name *.example.com. In all conf files certificate file path is set to the same cert file. 
What I expect is that I get a single wildcard cert that is to be reused by all subdomains.
What happens:
acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Error creating new order :: Domain name "something.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.

What I did to fix it:
change run_certbot.sh to look like that:
```
# Assemble the list of domains to be included in the request from
    # the parsed 'server_names'
    domain_request=""
    for server_name in "${server_names[@]}"; do
        if [[ $server_name == "*."* ]]; then
            domain_request="-d ${server_name}"
            break
        fi
        domain_request="${domain_request} -d ${server_name}"
    done
```

I'm not yet sure if that keeps the original functionality, so I don't think it's ready for pull request, but I just wanted to let everybody know that it can be "fixed" this way if needed.

**Comment by JonasAlfredsson** [comment]
Hi mikuslaw,

In order to help you a little bit better could you post the configuration files you have created as well as the complete log output from when the error occurred?

**Comment by mikuslaw** [comment]
Sure, 
I did some cleanup to anonymize, but it should show what is happening. The error is returned by letsencrypt server because we try to request a cert with both wildcard and a specific subdomain. So it's all as expected. The only problem is that we don't cleanup the cert request to limit the request just to the wildcard.
I think it may be hard to capture this situation in generic code - it depends both on the use of cert name and a set of domains (if it has a wildcard, and what other domains are captured by this specific cert name). So it may not be worth it to try to write a code that analyzes that and cleans up the request.

`
# root.conf
server {
    listen 443 ssl;
    server_name *.example.com;

    ssl_protocols TLSv1.1 TLSv1.2;

    # letsencrypt certificate
    ssl_certificate           /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/example.com/privkey.pem;

    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;

    access_log /var/log/nginx/example.com;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}
`
`
# subdomain.conf
server {
    listen 443 ssl http2;
    server_name subdomain.example.com;

    ssl_protocols TLSv1.1 TLSv1.2;

    # letsencrypt certificate
    ssl_certificate           /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/example.com/privkey.pem;

    ssl_verify_client off;
    
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;

    access_log /var/log/nginx/subdomain.example.com;

    location / {
        proxy_pass http://localhost:8889;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
`
`
docker-compose up
Creating nginx_sslproxy ... done
Attaching to nginx_sslproxy
nginx_sslproxy | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_sslproxy | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_sslproxy | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_sslproxy | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_sslproxy | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_sslproxy | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_sslproxy | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_sslproxy | Creating symlink '/etc/nginx/conf.d/root.conf' to '/etc/nginx/user_conf.d/root.conf'
nginx_sslproxy | Creating symlink '/etc/nginx/conf.d/subdomain.conf' to '/etc/nginx/user_conf.d/subdomain.conf'
nginx_sslproxy | Starting the Nginx service
nginx_sslproxy | Starting the autorenewal service
nginx_sslproxy | Starting certificate renewal process
nginx_sslproxy | Requesting an ECDSA certificate for 'example.com' (dns-01 through dns-route53)
nginx_sslproxy | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx_sslproxy | Renewing an existing certificate for subdomain.example.com and 1 more domains
nginx_sslproxy | Exiting abnormally:
nginx_sslproxy | Traceback (most recent call last):
nginx_sslproxy |   File "/usr/local/bin/certbot", line 8, in <module>
nginx_sslproxy |     sys.exit(main())
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/main.py", line 19, in main
nginx_sslproxy |     return internal_main.main(cli_args)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 1744, in main
nginx_sslproxy |     return config.func(config, plugins)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 1591, in certonly
nginx_sslproxy |     lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 129, in _get_and_save_cert
nginx_sslproxy |     renewal.renew_cert(config, domains, le_client, lineage)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/renewal.py", line 344, in renew_cert
nginx_sslproxy |     new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/client.py", line 441, in obtain_certificate
nginx_sslproxy |     orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/client.py", line 475, in _get_order_and_authorizations
nginx_sslproxy |     orderr = self.acme.new_order(csr_pem)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/acme/client.py", line 943, in new_order
nginx_sslproxy |     return cast(ClientV2, self.client).new_order(csr_pem)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/acme/client.py", line 704, in new_order
nginx_sslproxy |     response = self._post(self.directory['newOrder'], order)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/acme/client.py", line 103, in _post
nginx_sslproxy |     return self.net.post(*args, **kwargs)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/acme/client.py", line 1276, in post
nginx_sslproxy |     return self._post_once(*args, **kwargs)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/acme/client.py", line 1290, in _post_once
nginx_sslproxy |     response = self._check_response(response, content_type=content_type)
nginx_sslproxy |   File "/usr/local/lib/python3.9/dist-packages/acme/client.py", line 1136, in _check_response
nginx_sslproxy |     raise messages.Error.from_json(jobj)
nginx_sslproxy | acme.messages.Error: urn:ietf:params:acme:error:malformed :: The request message was malformed :: Error creating new order :: Domain name "subdomain.example.com" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.
nginx_sslproxy | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
nginx_sslproxy | Certbot failed for 'example.com'. Check the logs for details.
`

**Comment by JonasAlfredsson** [comment]
Alright, it is as I expected. 
I had a lengthy [discussion](https://github.com/JonasAlfredsson/docker-nginx-certbot/pull/94) with XaF about the complexity of filtering out which subdomain would be covered by which star certificate (and make sure it carries over between different configuration files), and I came to the conclusion that it would be too much work maintaining such a feature. 

However, my solution to this (which requires some manual intervention from you) is to add special comment that overrides the `server_name` declaration. You can look at the [example](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/examples/example_server_overrides.conf) where you can just add this to the troublesome config file: \
`server_name subdomain.example.com; # certbot_domain:*.example.com`

This would then solve your problem as far as I can see from the information you have provided here.

**Comment by mikuslaw** [comment]
I really like the solution you provided. I don't mind manual intervention and that gives me a very nice degree of flexibility. Thanks. 

I will extract common part of config. Makes sense. It's just my home server SSL proxy, so it's not a critical application, but I agree that is a much cleaner solution.
