### ISSUE TITLE
Certificate generation is failing

### ISSUE THREAD

**Issue by Eclegv** [JonasAlfredsson/docker-nginx-certbot#134]
I'm trying to generate 2 certificates for my domain and my subdomain, each of them don't have any special character, only [a-z].
But in the log there is 
`Requesting a certificate for xxxxxxx.cloud and 3 more domains`
So there are 2 that I don't know, and then, I have this error log
`acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "_": Domain name contains an invalid character`

**Comment by JonasAlfredsson** [comment]
Hi Eclegv,

It sounds like you have a line that looks like this in your config somewhere:

```
server_name _;
```

Can you upload all you config files here for me to look at them?

**Comment by Eclegv** [comment]
Ooooh I see, I fixed it !
Sorry for the inconvenience !
