### ISSUE TITLE
Certificate renewal fails

### ISSUE THREAD

**Issue by the-potato-church** [JonasAlfredsson/docker-nginx-certbot#137]
Hi!

I am using this docker container and everything works like a charm on initial setup, but the certbot certification request fails on renewal or even on rebuild unless I delete the ssl (`/etc/letsencrypt`) volume. The CA's return 404.

See the docker log output here:
```
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: ***
  Type:   unauthorized
  Detail: 3.8.149.8: Invalid response from https://***/.well-known/acme-challenge/fV7cZfjKV7GMaO5GsrHwXLpHRCsAItTxn8eVyTFc-T0: 404

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 1715, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 1574, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 127, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/renewal.py", line 344, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/client.py", line 441, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/client.py", line 493, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/auth_handler.py", line 106, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/auth_handler.py", line 206, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Certbot failed for '***'. Check the logs for details.
2022/09/02 10:44:45 [notice] 223#223: signal process started
2022/09/02 10:44:45 [notice] 94#94: signal 1 (SIGHUP) received from 223, reconfiguring
2022/09/02 10:44:45 [notice] 94#94: reconfiguring
2022/09/02 10:44:45 [notice] 94#94: using the "epoll" event method
Autorenewal service will now sleep 8d
2022/09/02 10:44:45 [notice] 94#94: start worker processes
2022/09/02 10:44:45 [notice] 94#94: start worker process 225
2022/09/02 10:44:45 [notice] 140#140: gracefully shutting down
```

I have also checked the cerbot log and the container is able to download the challenges, but fails to present them to the CA's.

Here is my docker compose configuration for the container:
```
  nginx-service:
    image: jonasal/nginx-certbot  # courtesy of https://github.com/JonasAlfredsson/docker-nginx-certbot
    restart: "always"
    depends_on:
      - ***
      - ***
    volumes:
      - ../***:/etc/letsencrypt
      - ../***:/logs
      - type: bind
        read_only: true
        source: ./nginx.conf
        target: /etc/nginx/user_conf.d/***.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
```

Any ideas on what is going wrong?

Thanks for the help!

**Comment by JonasAlfredsson** [comment]
If the `/etc/letencrypt` folder is empty, then the script will temporarily disable your custom `.conf` file so it is not active at all.
I am then reading this error message:

```
The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
```

So on succeeding runs it appears like the Let's Encrypt servers are unable to see the necessary files served by your Nginx instance. 
My suspicion is that when your config becomes active it somehow overwrite/overrule the default server listening on port 80 with something else. 

**Are you able to share your nginx.conf file here as well?**

**Comment by the-potato-church** [comment]
Hi!

Thanks for the swift reply! That was my suspicion as well - I was hoping that the script will disable the cusom nginx config every time.

Here is my nginx config:
```
upstream <a>{
   server                          ***;
}

upstream <b>{
   server                          ***;
}

server {
   server_name                    <domain>;
   access_log                      /logs/nginx-access.log combined;  # courtesy of https://business-science.github.io/shiny-production-with-aws-book/https-nginx-docker-compose.html

   location / {
            proxy_set_header        Host $http_host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              <a>;
            proxy_redirect          off;
   }

   location /*** {
            proxy_set_header        Host $http_host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_http_version      1.1;
            proxy_buffering         off;
            proxy_set_header        Upgrade $http_upgrade;
            proxy_set_header        Connection "Upgrade";
            proxy_pass              <a>/***;
   }

   location /***/ {
            rewrite                 ^/***/(.*) /$1 break;
            proxy_set_header        Host $http_host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass             <b>;
   }

   location /***/ {
            proxy_pass              ***;
   }

   listen                           443 ssl;

   # courtesy of https://github.com/JonasAlfredsson/docker-nginx-certbot
   ssl_certificate                  /etc/letsencrypt/live/<domain>/fullchain.pem;
   ssl_certificate_key              /etc/letsencrypt/live/<domain>/privkey.pem;
   ssl_trusted_certificate          /etc/letsencrypt/live/<domain>/chain.pem;
   ssl_dhparam                      /etc/letsencrypt/dhparams/dhparam.pem;

   ssl_protocols                    TLSv1.1 TLSv1.2;
   ssl_ciphers                      RC4:HIGH:!aNULL:!MD5;
   ssl_prefer_server_ciphers        on;
   keepalive_timeout                60;
   ssl_session_cache                shared:SSL:10m;
   ssl_session_timeout              10m;
}

server {
   server_name                      <domain>;

   listen                           80;
   return                          301 https://<domain>$request_uri;
}
```

The port 80 redirects to port 443 as for the application, I enforce the use of HTTPS. Any ideas on how to overcome this problem without needing to enable the HTTP comms?

Thanks!

**Comment by JonasAlfredsson** [comment]
The container already does this by default, it does not allow unencrypted access to anything else than the "well-known" folder required by Let's Encrypt. 

See this config: https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/nginx_conf.d/redirector.conf

So the solution for you is probably just to remove the server that listens to port 80 in your posted config.

**Comment by the-potato-church** [comment]
Great! Thank you very much for your help!

**Comment by JonasAlfredsson** [comment]
Also, unless you really need to support really old clients I would probably try to limit the TLS to >=1.2
https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by BurnsCommaLucas** [comment]
I'm in a very similar situation to potato church and I'm wondering if you can help me figure out why.

My nginx.conf is really simple:
```conf
http {
    server {
        listen 443 ssl;
        server_tokens off;
        gzip on;
        
        server_name  ***;

        ssl_certificate /etc/letsencrypt/live/***/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/***/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
            root /usr/share/nginx/html/homepage/;

            index index.html;
            proxy_intercept_errors on;
            error_page 400 500 404 https://***;
        }
    }
}
```

and in case it's relevant, the docker-compose file I'm using is
```
version: '3.7'
services:
  nginx:
    container_name: nginx-certbot
    restart: unless-stopped
    image: jonasal/nginx-certbot:4.2.0-nginx1.23.3
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx:/etc/nginx/
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/log/letsencrypt/:/var/log/letsencrypt/
    ports:
      - '80:80'
      - '443:443'
    environment: 
      CERTBOT_EMAIL: ***
      DEBUG: 1
    networks:
      - default
networks:
  default:
    name: docker_default
```

The root path just points to a folder of static html, and nginx from the docker image is able to serve the pages just fine, but when it tries to renew I get the same error:
```
nginx-certbot  | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
nginx-certbot  |   Domain: ***
nginx-certbot  |   Type:   connection
nginx-certbot  |   Detail: ***: Fetching http://***/.well-known/acme-challenge/ptF1kP9oAd87rE_sz_mKd-O4nVTQ88vI16tUavC5HkU: Connection refused
nginx-certbot  |
nginx-certbot  | Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
```

I've tried commenting out my entire `location / {}` block just to see if that would change anything, but it made no difference. Any thoughts you have would be appreciated but I know this is a pretty niche request so I understand if you can't take the time.

**Comment by JonasAlfredsson** [comment]
The certbot message says it gets `connection refused` when it tries to connect to `http://<your_domain>:80/.well-known/acme-challenge/<id>`

Do you have any firewall rules that blocks port 80 on your network?

**Comment by BurnsCommaLucas** [comment]
I do not, and testing the default redirect from `http://<site>` or `<site>:80` I get redirected properly to `https://<site>`. `netstat -atn` shows the system is listening on ports 80 and 443 on both ipv4 and ipv6 as well

**Comment by JonasAlfredsson** [comment]
Are you trying to reach your site through an external connection, i.e. can you try reach port 80 via your phone or similar so we don't run into any [fancy NAT setups](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/106#issuecomment-1040736752)?

After that I would try to go **into** the container and create a file similar to this:
```
echo "hi" > /var/www/letsencrypt/test.txt
```
and see if I could reach it through `http://<your_domain>:80/.well-known/acme-challenge/test.txt`

**Comment by BurnsCommaLucas** [comment]
I'm doing all this development on a remote server, so docker is running on that server and I'm testing the access from my personal computer. I believe that should prevent any of the NAT behavior you linked before, but I can try other methods if that doesn't seem sufficient.

I created the file within the container and when I navigated to `http://<site>:80/.well-known/acme-challenge/test.txt` I got an immediate `302` redirect to `/`:
![302](https://user-images.githubusercontent.com/9172192/222988365-5bf36e97-1329-4b7a-9c67-718ce0e91944.jpg)

**Comment by JonasAlfredsson** [comment]
You should not be receiving any redirects on that path, here is how it should look in case the file does not exist:

```
curl -Lvvv http://<my_site>/.well-known/acme-challenge/test.txt
*   Trying 1.2.3.4:80...
* TCP_NODELAY set
* Connected to <my_site> (1.2.3.4) port 80 (#0)
> GET /.well-known/acme-challenge/test.txt HTTP/1.1
> Host: <my_site>
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx/1.23.3
< Date: Sun, 05 Mar 2023 22:15:58 GMT
< Content-Type: text/html
< Content-Length: 153
< Connection: keep-alive
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
</html>
```

The Nginx logs should look something like this:

```
2023/03/05 22:13:45 [error] 248#248: *124 open() "/var/www/letsencrypt/.well-known/acme-challenge/test.txt" failed (2: No such file or directory), client: 9.8.7.6, server: , request: "GET /.well-known/acme-challenge/test.txt HTTP/1.1", host: "<my_site>"
9.8.7.6 - - [05/Mar/2023:22:13:45 +0000] "GET /.well-known/acme-challenge/test.txt HTTP/1.1" 404 153 "-" "curl/7.68.0" "-"
```

And I gave the wrong path in the message before, you should place the file in `/var/www/letsencrypt/.well-known/acme-challenge/text.txt`

**Comment by BurnsCommaLucas** [comment]
So I re-created the container, re-created the directories and file in the revised location, tested again and I still get a 302. 

Curiously, the nginx logs indicate it's looking in the `root` path defined by my `location / {}` rule of `/usr/share/nginx/html/homepage` for the directory:
```
2023/03/05 23:46:59 [error] 20#20: *1 open() "/usr/share/nginx/html/homepage/.well-known/acme-challenge/test.txt" failed (2: No such file or directory), client: ***, server: ***, request: "GET /.well-known/acme-challenge/test.txt HTTP/1.1", host: "***"
```
and if I disable my `location / {}` rule, I see a very similar error but it appears to be looking in `/etc/nginx/html` this time

```
2023/03/05 23:53:00 [error] 19#19: *2 open() "/etc/nginx/html/.well-known/acme-challenge/test.txt" failed (2: No such file or directory), client: ***, server: ***, request: "GET /.well-known/acme-challenge/test.txt HTTP/1.1", host: "***"
```

**Comment by JonasAlfredsson** [comment]
Wait, are you overwriting the main `/etc/nginx/nginx.conf` file?
You are not supposed to do that, but rather use the `nginx_conf.d` to add your custom `server` blocks.

Read these short sections: 
1. https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#creating-a-server-conf-file
2. https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#the-user_confd-folder
3. https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/nginx_tips.md#how-nginx-loads-configs

**Comment by BurnsCommaLucas** [comment]
Ah yeah that's the issue. Since I was forwarding all of `/etc/nginx`to the container rather than just `/etc/nginx/user_conf.d`, a previous version of my conf that lived at the root of `/etc/nginx` was getting picked up unintentionally. Changing my docker compose to match the readme (`${pwd}/user_conf.d:/etc/nginx/user_conf.d:ro`) fixed things

Sorry about the noise, but I really appreciate the help!

**Comment by JonasAlfredsson** [comment]
Sweet, happy to have been of assistance :)
