### ISSUE TITLE
Auto-renew certs for domain and subdomain? 

### ISSUE THREAD

**Issue by WilliamBehrens** [JonasAlfredsson/docker-nginx-certbot#139]
Say I have `example.com` and `ci.example.com` with this setup how would I go about getting certificates for both domains if they're running on the same box?

**Comment by JonasAlfredsson** [comment]
Take a look at the [simple example](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/examples/example_server.conf) how the Nginx server is configured to respond to both domains. The scripts will then find both those names and add them to the certificate request, simple as that :)
