### ISSUE TITLE
Unknown FileSystemError with `privkey.pem`

### ISSUE THREAD

**Issue by robertsLando** [JonasAlfredsson/docker-nginx-certbot#141]
I'm running this container with `USE_LOCAL_CA` env var set. I have `/etc/letsencrypt` folder mapped to a local folder.

When restarting container it always fail to restart and the error is that privkey.pem in invalid, in fact if I try to open that file I get the error mentioned in the title. Any clue?

**Comment by JonasAlfredsson** [comment]
Hi robertsLando,

If possible, can you paste the raw terminal output for me to see? 

One thought is that perhaps the privkey failed to be properly written and it is corrupted. Something you could try is to delete the file (and the certificate) and restart everything again.

**Comment by robertsLando** [comment]
> One thought is that perhaps the privkey failed to be properly written and it is corrupted. Something you could try is to delete the file (and the certificate) and restart everything again.

Yeah that is what I do to restore BTW I would like to find a way to prevent this to happen

Will report this back as soon as I can reproduce it, seems that is not happening every time

**Comment by JonasAlfredsson** [comment]
Have you managed to run into this issue again?

After reading your other issue I guess you could add this entrypoint script (which assumes that you always do the initial boot with DOMAIN=loclhost)

```bash
if [ -d /etc/letsencrypt/live/localhost ]; then
  rm -rvf /etc/letsencrypt/live
fi
```

This would reset the entire "live" folder if there has been a localhost domain present, which would have required a self signed certificate. You can go even harder and probably change "live" to "*" for even better purge effect.

**Comment by robertsLando** [comment]
I haven't managed to reproduce this issue anymore and that's strange as I didn't changed anything on first sight that could have fix it. 

I have a feel that could be something related to a `nginx -s reload` command I do from another docker container when it successfully starts the webserver. 

I have to do it because there is an issue with nginx when the upstream server starts too late it will fail to proxy requests with `[emerg] host not found in upstream "api"`. Tried to use some solutions with resolver like suggested [here](https://stackoverflow.com/questions/42720618/docker-nginx-stopped-emerg-11-host-not-found-in-upstream/52319161#52319161) without luck

**Comment by JonasAlfredsson** [comment]
If the container starts with upstream servers missing Nginx will panic and exit which will bring the whole container down with it. That could be a reason why a corrupted file was created. 

I would also suggest you do a `docker kill --signal=HUP` instead of a nginx reload, as this will go through my scripts instead of going directly to the nginx binary.

**Comment by JonasAlfredsson** [comment]
How are you starting the containers?
Because doesn't docker-compose have a "depends-on" setting for bringing stuff up in a specific order?

**Comment by robertsLando** [comment]
> I would also suggest you do a docker kill --signal=HUP instead of a nginx reload, as this will go through my scripts instead of going directly to the nginx binary.

I think this could be better. Thanks!

> Because doesn't docker-compose have a "depends-on" setting for bringing stuff up in a specific order?

I'm using docker-compose, the problem is that it could be for some reason the webserver container needs to be restarted, in the meanwhile I have created a dedicated 502 error page that explains this to the user when this happens and automatically refreshes the page when the webserver comes back online. I know that with the depends_on setting I could prevent the problem problem by setting nginx depending on webserver but cannot use that for the reason I just explained

**Comment by JonasAlfredsson** [comment]
But the depends-on stuff should only be relevant the first time all the containers are started right?
When everything is up and running you can just target the single api container and restart it, and since Nginx doesn't re-resolve upstream names (without some tweaking) it shouldn't care that the other container is offline?

**Comment by robertsLando** [comment]
> But the depends-on stuff should only be relevant the first time all the containers are started right?
When everything is up and running you can just target the single api container and restart it, and since Nginx doesn't re-resolve upstream names (without some tweaking) it shouldn't care that the other container is offline?

Problem would not be fixed because `depends_on` doesn't wait for the container to be 'ready' (server listening on the port) but it only start nginx right after the web server container is started. This is a problem as the webserver container could take a while to start as it has to check migrations and all other containers setup (sometimes it also need to create certificates and keys for some openvpn containers), this brings us back to the original issue making depends_on useless.

Anyway I'm going to close this, I never faced again the main issue reported here, I think that using the signal kill instead of reloaoding nginx fixed it!

I really thank you for your support and this awesome package! ❤️

**Comment by JonasAlfredsson** [comment]
Sure thing, just open a new issue if there is something else :)
