### ISSUE TITLE
Remove Server Header from Nginx

### ISSUE THREAD

**Issue by nazari-ali** [JonasAlfredsson/docker-nginx-certbot#155]
Hi

How can I delete the server header for nginx?
Thankful

**Comment by nazari-ali** [comment]
Hi,
Thank you for responding

I want the server name to be completely removed, I use the "server_tokens off;" command in my attachment file I can only remove the Nginx version.

I used the links below to remove the Nginx name, but I ran into problems every time.

https://www.cyberciti.biz/faq/hide-nginx-version-in-linux-and-unix/
![image](https://user-images.githubusercontent.com/40435607/206552216-d16581e9-e9f4-4753-9e17-aa983ac98466.png)

https://itecnotes.com/server/linux-how-to-disable-server-and-server-tokens-header-parameters-on-nginx/
![image](https://user-images.githubusercontent.com/40435607/206552080-085f9c72-4a9d-4cae-b371-714447f06d56.png)

https://www.appsloveworld.com/docker/100/27/how-can-i-remove-server-header-in-nginx-docker-container
![image](https://user-images.githubusercontent.com/40435607/206552343-6ec610ae-066d-4717-b269-d892eb833e5e.png)

**Comment by JonasAlfredsson** [comment]
So you want to remove the "Server: Someting" that is transmitted in the request.
And option 1 does not work on the Nginx version this image is based on?

Option 2 is one alternative if you are felling adventurous, you could probably look at the parent containers build scripts.
Option 3 will not work in with the parent Image we are based on, see https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/154 for further discussion.

I have not looked into this particular setting as I have never thought about turning it off, so I don't really have a lot of input to this issue, sorry :/

**Comment by nazari-ali** [comment]
For Option 2, can you guide me on what to do?

**Comment by JonasAlfredsson** [comment]
I would start at looking at the [parent container's Dockerfile](https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile), and then see where in those steps the guide you linked would fit in. 

However, recompiling Nginx is not really anything I have done, but I think there is a guide on the [Nginx official page](https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/) you can look at.

**Comment by nazari-ali** [comment]
Hi,

This worked for me without any problems.

`sed -i 's/Server: nginx/My-Header: hi/' `which nginx``

**Comment by JonasAlfredsson** [comment]
Cool! Great find!
