### ISSUE TITLE
ipv6 unable to bind :81

### ISSUE THREAD

**Issue by odin568** [JonasAlfredsson/docker-nginx-certbot#160]
Hey,
I get this with the latest version from today v3.3.0 as a problem resulting from #159 
```
Starting the Nginx service
Starting the autorenewal service
2022/12/30 21:08:06 [emerg] 88#88: bind() to [::1]:81 failed (99: Cannot assign requested address)
nginx: [emerg] bind() to [::1]:81 failed (99: Cannot assign requested address)
```
My conf you can see here: https://github.com/FFW-Baudenbach/FE2_ReverseProxy/blob/main/conf.d/haus.ffw-baudenbach.conf
Not sure if 
```
listen [::]:443 ssl http2 default_server reuseport;
```
might be the issue?

**Comment by tvhdev** [comment]
This "feature" seems to break everything, please remove it!

**Comment by tvhdev** [comment]
> Hey, I get this with the latest version from today v3.3.0 as a problem resulting from #159
> 
> ```
> Starting the Nginx service
> Starting the autorenewal service
> 2022/12/30 21:08:06 [emerg] 88#88: bind() to [::1]:81 failed (99: Cannot assign requested address)
> nginx: [emerg] bind() to [::1]:81 failed (99: Cannot assign requested address)
> ```
> 
> My conf you can see here: https://github.com/FFW-Baudenbach/FE2_ReverseProxy/blob/main/conf.d/haus.ffw-baudenbach.conf Not sure if
> 
> ```
> listen [::]:443 ssl http2 default_server reuseport;
> ```
> 
> might be the issue?

Dude, just use another version, like 3.2.2, this one seems to work

**Comment by JonasAlfredsson** [comment]
Thank you for informing me, it worked for me and I thought Nginx would understand if no IPv6 was available (like in the [redirector.conf](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/nginx_conf.d/redirector.conf)).
This has been reverted and is building as we speak.

Will try to experiment more with this before pushing again.

**Comment by JonasAlfredsson** [comment]
Version 3.3.1 should now be up where this is reverted. 
Sorry for pushing this right before new years. :)

**Comment by tvhdev** [comment]
@JonasAlfredsson Thank you for your hard work and fixing the error. Happy new year 2022!
