### ISSUE TITLE
Support IPv6 for the HTTP-01 ACME challenge

### ISSUE THREAD

**Issue by JonasAlfredsson** [JonasAlfredsson/docker-nginx-certbot#161]
In [#159](https://github.com/JonasAlfredsson/docker-nginx-certbot/pull/159) it was attempted to add IPv6 support to the `certbot.conf` server, however, this [broke setups](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/160) which did not have IPv6 enabled. 

I will therefore take the discussion from [#53](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/53) and just drops the entire `certbot.conf` file. This is *actually* a breaking change for those who have overwritten this file with something custom, but I think those are few and a major version bump should have them be prepared for it.

**Comment by JonasAlfredsson** [comment]
@Meptl, let's continue the discussion here if/when you respond :)

I just pushed [this](https://github.com/JonasAlfredsson/docker-nginx-certbot/commit/a35f3be276e9393217937fc7dc44751751adb5fa) to the :dev`` tag on DockerHub, could you test it out on your system as well?

**Comment by JonasAlfredsson** [comment]
Perhaps @odin568 would like to test out the `:dev` branch as well? :)

**Comment by Meptl** [comment]
jonasal/nginx-certbot:dev works on my system!

**Comment by odin568** [comment]
At least it does not break anything when running. Did not test certificate renewal but at least nginx itself works with my config now.

**Comment by JonasAlfredsson** [comment]
Sweet, then we try this stunt again ^^

**Comment by JonasAlfredsson** [comment]
Well, it seems noone started screaming after the last update so I suppose it was a success :)
