### ISSUE TITLE
Can not override client_max_body_size, proxy_read_timeout etc. via user_conf.d configs

### ISSUE THREAD

**Issue by w7rus** [JonasAlfredsson/docker-nginx-certbot#164]
Steps to reproduce:

```
server {
        # Listen to port 443 on both IPv4 and IPv6.
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        # Domain names this server should respond to.
        server_name yourwebsite.net;

        client_max_body_size 100M;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        client_header_timeout 300s;
        client_body_timeout 300s;
        large_client_header_buffers 256 8k;
        keepalive_time 1h;
        keepalive_timeout 300s;

        # Load the certificate files.
        ssl_certificate         /etc/letsencrypt/live/test-name/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/test-name/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/test-name/chain.pem;

        # Load the Diffie-Hellman parameter.
        ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

        location / {
                proxy_pass http://host.docker.internal:6000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection keep-alive;
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
}
```
Config loads fine, no errors in logs:

Sending 27,828,544 bytes file:
``[error] 576#576: *16 client intended to send too large body: 27828776 bytes``

Uploading a file less than 1MB works fine.

That means that directives used under user_conf.d configs like ``client_max_body_size`` are skipped for some reason.

Current temporary fix (patch original repo):
* Cloning repository
* Creating ``nginx.conf`` file from *runtime created* ``nginx.conf`` in nginx-certbot container file & adding required directives to ``http {}``
* Add ``COPY nginx.conf /etc/nginx/nginx.conf`` to Dockerfile
* Building custom image & running it
* It works!

I intent to upload & download large files >= 1G

**Comment by JonasAlfredsson** [comment]
Hi w7rus,

This container does nothing to the configs placed in the `conf.d/` folder, so I have no idea why it is not picked up by Nginx. A [quick search](https://stackoverflow.com/questions/2056124/nginx-client-max-body-size-has-no-effect) suggested that in a very old Nginx version you had to place it in the `http` block for it to have effect, 

You can achieve this by creating a config that is [loaded before](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/nginx_tips.md#how-nginx-loads-configs) your server config with the line 
```
client_max_body_size 100M;
```

**Comment by w7rus** [comment]
Okay, gonna do the mount way of overriding via custom nginx.conf. Thanks.
