### ISSUE TITLE
Nginx with Http/3 + QUIC support

### ISSUE THREAD

**Issue by 69teen** [JonasAlfredsson/docker-nginx-certbot#175]
I would like to request Nginx built with HTTP/3 + QUIC support as a separate image tag.

HTTP/3 is the latest HTTP protocol version and offers significant performance improvements over its predecessors. Adding HTTP/3 support to Nginx allows taking advantage of these improvements and provides a faster and more efficient web experience.

I understand that adding HTTP/3 support may require additional configuration and dependencies. However, I believe that the benefits of supporting this new protocol outweigh the potential difficulties.

Thank you for considering my request. I look forward to hearing back from you.

**Comment by JonasAlfredsson** [comment]
Hi 69teen,

I base my images on the official Nginx ones so I don't have to compile Nginx myself. This significantly reduce the work I need to do, and I do not need to keep up to date with the latest compile arguments and Dependabot gives me automatic pull requests as soon as Nginx official updates their images. This also means that it is basically transparent for users to jump between the official images and this one, and they can look at the layers to see that I don't tamper with anything from the official image. 

So I am not really interested in maintaining a separate fork of custom compiled Nginx for this, but would rather wait until it is included in the mainline release. It does not seem that far of if I read these correctly:
- https://quic.nginx.org/
- https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/
- https://www.nginx.com/blog/our-roadmap-quic-http-3-support-nginx/

**Comment by JonasAlfredsson** [comment]
I will close this since we will just wait until the parent container gets there and we will just follow :)
