### ISSUE TITLE
Handshake failed with `-alpine` nginx images

### ISSUE THREAD

**Issue by robertsLando** [JonasAlfredsson/docker-nginx-certbot#184]
I have a device that support max TLSv1.0, I have this directive in my nginx conf file:

```
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
        ssl_prefer_server_ciphers on;
```

It always worked with non alpine image but when I switch to a whatever `-alpine` image all request fail with `handshake failed` error.

This is reprodicible and it's for sure something related to alpine containers only

**Comment by JonasAlfredsson** [comment]
From the parent container: https://github.com/nginxinc/docker-nginx/issues/743

If you absolutely need TLS 1.0 then the Debian image is currently your solution. However, I would really recommend you to move to TLS 1.2 as soon as possible since I believe Debian will also stop supporting this in the near future.

**Comment by robertsLando** [comment]
Thanks for your answer Jonas, I know about the security implications but unfortunally the application must be back compatibile with some very old edge device that doesn't support an higher TLS version (for now). The idea is to make them supported right now and remve it in a future release so at least there is the possibility to update them using this application

BTW It's ok for me, I will just stay stiky with the debian version for now until I can remove the back compatibility. Thanks 🙏🏼

**Comment by JonasAlfredsson** [comment]
It _should_ include it:

```
docker run -it --entrypoint=/bin/bash jonasal/nginx-certbot:4.2.0 --version                                        
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
```

Testing with the HUP signal on the container it works as expected.

Do we need to add some kind of "if empty file check" as well?

**Comment by robertsLando** [comment]
> Do we need to add some kind of "if empty file check" as well?

I think so, I cannot reproduce this easily but a double check would be for sure a good thing

**Comment by JonasAlfredsson** [comment]
Please open a new issue and reference this. 
We can probably make something out of this check: https://stackoverflow.com/a/9964890

**Comment by JonasAlfredsson** [comment]
But do you have a `stat` information about the file that cause trouble. That way we can verify it actually has a size of zero when it happens.

**Comment by robertsLando** [comment]
I temporary changed to another nginx-certbot version btw I'm sure it was size 0
