### ISSUE TITLE
[bug] Empty `privekey.pem`

### ISSUE THREAD

**Issue by robertsLando** [JonasAlfredsson/docker-nginx-certbot#185]
Opened a new issue as requested: https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/184#issuecomment-1534840085

> I switched to Debian based version but seems I still get the error related to #165

Does 4.2.0 includes the fix?

**Comment by JonasAlfredsson** [comment]
It should include it:

```
docker run -it --entrypoint=/bin/bash jonasal/nginx-certbot:4.2.0 --version                                        
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
```

Testing with the HUP signal on the container it works as expected.

I have now added an additional "non-empty" file check.

**Comment by JonasAlfredsson** [comment]
The 4.2.1 tag is now built and uploaded :)

**Comment by robertsLando** [comment]
Thanks Jonas 🙏🏼
