### ISSUE TITLE
NGINX started multiple times after certificate renewal check

### ISSUE THREAD

**Issue by Nyffeneggerr** [JonasAlfredsson/docker-nginx-certbot#188]
Hi
On my VMs, where I use the docker-nginx-certbot docker image, I can see that after the regular certificate renewal check, the docker container is using the double amount of memory. Due to memory constraints, it works for 2 renewals, then the container crashes with an OutOfMemory exception.
After some investigation I found out that after the renewal-check, there are 2 running NGINX instances in the same container, using both the same amount of memory.
Is this an issue or am I doing something wrong?

![image](https://github.com/JonasAlfredsson/docker-nginx-certbot/assets/36026352/95877977-3ab4-4986-8211-b437691bddc0)

**Comment by JonasAlfredsson** [comment]
Nginx has one "main" process, and then one worker per CPU (if set to [automatic](https://docs.nginx.com/nginx/admin-guide/basic-functionality/runtime-control/)).

This is how it looks on my 8 core machine:
```
ps fax | grep nginx

    1 pts/0    Ss+    0:00 /bin/bash /scripts/start_nginx_certbot.sh
   38 pts/0    S+     0:00 nginx: master process nginx -g daemon off;
  411 pts/0    S+     0:00  \_ nginx: worker process
  412 pts/0    S+     0:00  \_ nginx: worker process
  413 pts/0    S+     0:00  \_ nginx: worker process
  414 pts/0    S+     0:00  \_ nginx: worker process
  415 pts/0    S+     0:00  \_ nginx: worker process
  417 pts/0    S+     0:00  \_ nginx: worker process
  418 pts/0    S+     0:00  \_ nginx: worker process
  419 pts/0    S+     0:00  \_ nginx: worker process
   39 pts/0    S+     0:00 /bin/bash /scripts/start_nginx_certbot.sh
```

After a reload Nginx starts new worker processes with the new configuration settings, but lets the old processes shut down in a controlled fashion. This means that if there are clients that holds a TCP connection open the old worker will remain active until all of its connections are terminated: https://www.ruby-forum.com/t/memory-usage-doubles-on-reload/239590/2

**Comment by JonasAlfredsson** [comment]
How often do you reload, and what type of clients connect to you?
Because it seems weird if they hold a connection open for the 8 days reload cycle that is default.

**Comment by Nyffeneggerr** [comment]
Ah yes that would explain the behavior to me. We are controlling a huge amount of sensors that maintain a persistent connection (Websocket) to our service (trough NGINX). This connection stays open as long as the VM is available (until restart/crash or whatever).
What do you think, would it make sense in this case to increase the renewal interval? Or do you see some other solution?

**Comment by Nyffeneggerr** [comment]
Or would it be possible to force the termination of the "old" process?

**Comment by JonasAlfredsson** [comment]
Depends on what you value here.

Let's Encrypt certificates are valid for 90 days, so you could probably set it to 85 days or so, but [read this](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#renewal-check-interval) first.
However, this still has the issue that your clients will continue to hold that connection open, so if they do not restart/reconnect during another 80 days you will run in to the same issue again.

I don't find any information on how to "forcefully" reload Nginx, so the next best thing would perhaps be to restart the container, which terminates everything and starts up again with new certificates. This means that you will have some downtime (seconds) but if your clients can handle that, then it would work.

**Comment by JonasAlfredsson** [comment]
You could probably write some own logic which tries to kill long lived processes, but I believe that is out of scope of the scripts I provide.

**Comment by JonasAlfredsson** [comment]
Reading some more configs it might be worth to try setting [worker_shutdown_timeout](http://nginx.org/en/docs/ngx_core_module.html), it seems to give the workers a hard deadline before they are killed. It will cause some minor hiccups for the connected clients, but if they handle reconnects properly it should not be an issue.

**Comment by Nyffeneggerr** [comment]
Thanks again, I will definitely give that setting a try. And if not working, I will ensure to restart the container once per month.

**Comment by Nyffeneggerr** [comment]
Just as an information, I tested the _worker_shutdown_timeout_ and it works perfectly. The devices are disconnected as desired and the memory 'leak' is gone. Everything fine, thanks a lot for your help!
