### ISSUE TITLE
config file not being discovered

### ISSUE THREAD

**Issue by Olaaa30** [JonasAlfredsson/docker-nginx-certbot#215]
I have my nginx.conf file in a parent directory-"nginx". When I run my deployment pipeline, dockercompose just copies the parent "nginx" directory. Please take a look at the project here: https://github.com/Ocean-Db/fast-API/blob/main/docker-compose.yml
Your feedback would be highly valuable.
Thanks in anticipation

**Comment by JonasAlfredsson** [comment]
On my phone so keeping it short :)

Remove the server block for port 80 and try again.

If that does not work you need to copy paste the logs here for me to see.

**Comment by Olaaa30** [comment]
Hi, thanks for you response. Removing the server block for port 80 didnt work but 
I was able to find a work around by including the nginx.conf file in the cicd pipeline

**Comment by JonasAlfredsson** [comment]
Ah, looking at your deployment scripts you copy the `docker-compose.yml` file to a target host and then execute that. If you did not include the nginx.conf file in your copy step you would not be able to read it on the target server.

**Comment by Olaaa30** [comment]
Yeah, I eventually realized that😅. Thanks for your insights
