### ISSUE TITLE
Update Dockerhub Image

### ISSUE THREAD

**Issue by Fummowo** [JonasAlfredsson/docker-nginx-certbot#216]
Update Dockerhub image to fix issues with DNS plugins: https://github.com/certbot/certbot/pull/9821
I have built the alpine image locally for now and can confirm the issue is fixed and believe others would benefit from this too :)

**Comment by JonasAlfredsson** [comment]
Hi  Fummowo, 

So there is already a certbot PIP package ready for download which includes the above mentioned fix?
If that is the case we can rebuild the `latest` immediately, but I don't know if we should do a minor bump for the tagged version (even though we have not done something like that before).

**Comment by Fummowo** [comment]
Yes, the cerbot PIP backage was recently updated with the fix :) and I agree with the versioning :)

**Comment by JonasAlfredsson** [comment]
latest tag should now have been rebuilt, but I will just need a little more time to think about how to best proceed with the tagged rebuild :)

**Comment by JonasAlfredsson** [comment]
We will now update the patch version when certbot is updated: https://github.com/JonasAlfredsson/docker-nginx-certbot/pull/228
