### ISSUE TITLE
How is log rotation handled?

### ISSUE THREAD

**Issue by Winfred-zz** [JonasAlfredsson/docker-nginx-certbot#231]
How is logrotation handled?

By default NGINX does not rotate logs and delete old logs.

Will this just fill up the drive over time?

**Comment by JonasAlfredsson** [comment]
Log rotation is usually out of scope of the program, but in the Nginx case the parent image symlinks the default logs to print to [stdout and stderr](https://github.com/nginxinc/docker-nginx/blob/master/mainline/debian/Dockerfile#L102). When running inside a container all this output is then managed by Docker, which you can [configure](https://docs.docker.com/config/containers/logging/configure/) to keep a certain amount of log before throwing them away.

**Comment by mymy-dot** [comment]
Thanks for clarifying and for providing the docker image, has been really handy for me.

**Comment by Winfred-zz** [comment]
Thanks for clarifying and for providing this awesome image.
