### ISSUE TITLE
Reload nginx config without forced certificat renewal?

### ISSUE THREAD

**Issue by aschneider** [JonasAlfredsson/docker-nginx-certbot#236]
Hello there, thank you for providing this excellent image which I have been using for years!

I am using nginx as a proxy for my homelab to have all services routed over the nginx proxy with a dedicated subdomain that then serves some other dedicated IPs and ports. 

However since I do have a whole bunch of services which are all located in one nginx config, I increasingly have issues with rate limiting, especially this one:

`acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours:`

If I understand correctly and judge the way the wait time is implemented by a sleep of x amount of time, this means that every time I do change something in my nginx config and then have the docker container restart in order to reload the config, certbot will then try to renew each and all of the existing server names. Which then leads to this error. 

How do I get around this issue? Shouldnt certbot somehow "know" when it last tried a domain? Or can I somehow persist the renewal time window (does not look like it with the while; true; sleep approach) 

or can I reload the nginx config w/o triggering the certificate renewal so I can selectively renew a service when I add them without triggering a renewal on all the "untouched" ones?

Thank you!

**Comment by JonasAlfredsson** [comment]
Hi aschneider,

Hmmm, I thought certbot was clever enough to figure that stuff out. Are you adding and removing domains in the config when you are doing changes so there is actually a diff in the renewal request made?

Also, you should not need a restart of the container to reload configs, it should be enough with a `docker kill --signal=HUP <conatiner>` to have everything do a hot reload. If you are interested in only reloading nginx (and not trigger any renewal checks) you can target Nginx directly via `docker exec -it <conatiner> nginx -s reload`.

**Comment by JonasAlfredsson** [comment]
Because we do use this setting, which I read as no update will be made to the certificate unless needed

```
automation:
  Flags for automating execution & other tweaks

  --keep-until-expiring, --keep, --reinstall
                        If the requested certificate matches an existing
                        certificate, always keep the existing one until it is
                        due for renewal (for the 'run' subcommand this means
                        reinstall the existing certificate). (default: Ask)
```

**Comment by aschneider** [comment]
Hello Jonas, 

thank you for the response appreciated!

what I am doing is usually adding one such block to my config. Always creating a new subdomain in my TLD for the new service I came up with. And then pointing it to some host:port in my home lab. 

`server {
    listen 443 ssl;
    server_name <newsubdomain>.mytld.com;

    ssl_certificate     /etc/letsencrypt/live/<newsubdomain>.mytld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<newsubdomain>.mytld/privkey.pem;

   ... some SSL setting ...
   
    access_log            /var/log/nginx/<newsubdomain>.mytld.access.log;

    location / {
       ... some proxy headers...
       
        proxy_pass          http://10.10.10.230:80; 
        proxy_redirect      http://10.10.10.230:80 https://<newsubdomain>.mytld.com;
    }
}`

important to note, I have one big old nginx.conf file where I am adding all the servers currently. I was wondering whether it would make a difference for certbot if all definitions were in a separate conf file? Anything else I am doing here that might screw with certbot?

I am quite hesitant to troubleshoot and test different ways here, because if it goes wrong I am quickly locked out by letsencrypt and I have a couple of services that do have production users whilst others are homeassistant or other non important stuff. Ans switich to staging does not make the issue visible and switching back requires new certs and therefore the issue is even more prominent.

I will try the nginx reload mechanism though, thank you! That way I can add a service, which wont get a cert until the next renewal run is scheduled - which schould be fine I guess!

**Comment by JonasAlfredsson** [comment]
I am not at my computer right now so can't give you any nice links, but I the docs there should be information regarding how my scripts assemble the requests, and what limits Let's Encrypt impose. 

I think you will benefit from splitting into smaller configs, where all servers in one config shares the same certificate. 

Also, if you read the advanced docs you can find information on how you can override my scripts in case you want to issue a star certificate instead, which means you can reuse the same one for all servers.

**Comment by aschneider** [comment]
Wildcard Cert sounds interesting! Did not know that was possible with let's encrypt. That might solve the issue entierly. I'll consult the docs and report back. Thank you!

**Comment by aschneider** [comment]
the splitting up in separate nginx files has already worked. I seem to be able to request much more certs than before without running into any limits. Using wildcard did not work for me since my domain/dns hoster "united domains" does not seem to be supported. 
So having one big conf file seems to request for each server name with the names of all the domains and therefore produces parallel requests. 

Thank you very much for your assistance, appreciated!

**Comment by JonasAlfredsson** [comment]
Glad it was as simple as that. 

However, if you want to add support for your DNS provider I am open for pull requests :)
