### ISSUE TITLE
Cryptography failed to build

### ISSUE THREAD

**Issue by RtKelleher** [JonasAlfredsson/docker-nginx-certbot#24]
Installed on Raspberry Pi 4, ARM7, 8gb

Consider adding Cargo and pep517 as my build failed building cryptography without them. Other than those two dependencies it ran great. 

`  This package requires Rust >=1.41.0. ERROR: Failed building wheel for cryptography`

`ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly`

**Comment by JonasAlfredsson** [comment]
Hi RtKelleher, 

I do not own a Raspberry Pi, so I have not had the chance to run into this issue before.
Would you mind helping me debug this? I will see if I can get hold of such a device, but until then could you post the entire build output here?

Best regards
Jonas

**Comment by JonasAlfredsson** [comment]
I have been doing some experimenting with Buildx and QEMU, and would just like to double check with you about one thing:
It was enough to just add "cargo" to the installed dependencies for the build process to succeed right?

**Comment by JonasAlfredsson** [comment]
I have now spent some time trying to build this architecture via QEMU, and I think I have been successful (see issue mentioned above).
So you should now be able to pull my image directly from DockerHub, if you do not want to build it yourself locally. 

As I said in the beginning, I don't have a RPi, so I would greatly appreciate if you could test this when you have time :)

**Comment by odin568** [comment]
V1.2.0 runs great on my Raspi 3b+ (arm/v7)

**Comment by JonasAlfredsson** [comment]
Excellent!
Then I will close this issue :)
