### ISSUE TITLE
adding additional info in the http directive

### ISSUE THREAD

**Issue by LorenzoNey** [JonasAlfredsson/docker-nginx-certbot#243]
Hi,

Is there an elegant way to add additional info to the main nginx.conf file without custom-mapping a new file on top of the one included in the container?

setting such as:

`limit_req_zone $binary_remote_addr zone=ms_rate_limit:10m rate=5r/s;`

which cannot be defined in conf.d files

Thank you

**Comment by JonasAlfredsson** [comment]
Hi LorenzoNey,

That is probably a question best directed at the [parent container](https://github.com/nginxinc/docker-nginx). This image does minimal changes beyond adding certbot, and unfortunately I know of no "good" way of injecting stuff to the main configuration file without resorting to mounting your own file or doing something with `sed` through [entrypoint.d](https://github.com/nginxinc/docker-nginx/tree/master/entrypoint) scripts.

**Comment by LorenzoNey** [comment]
Hi @JonasAlfredsson 
That's cool, thanks for letting me know, I'll do that 👍

**Comment by JonasAlfredsson** [comment]
Did you find a solution that worked?

**Comment by LorenzoNey** [comment]
Hey @JonasAlfredsson not yet.. I was looking for other solutions, like caddy. I'm still toying with it..
