### ISSUE TITLE
How do you migrate from staticfloat/docker-nginx-certbot?

### ISSUE THREAD

**Issue by monarchwadia** [JonasAlfredsson/docker-nginx-certbot#25]
Hi! Thanks for essentially taking over the project!

How does one migrate from staticfloat's docker image? Is it as simple as changing the image name from `staticfloat/docker-nginx-certbot` to `JonasAlfredsson/docker-nginx-certbot`? Or is more work needed?

Perhaps it would be good to add this info to README?

Thank you in advance for your reply.

**Comment by JonasAlfredsson** [comment]
Hi monarchwadia,

Thank you, I will try my best to carry on the legacy from staticfloat :)

I think the process should be as easy as just taking you old `nginx_conf.d/*` files and placing them in the same location in my repository. If you have your own Dockerfile I suspect it will be as easy as just changing the image name. 

It is not a bad idea to perhaps add some short notes about this now when there is actually a redirect to here from another repo. I will see what I can whip up!
