### ISSUE TITLE
How to add a wildcard SAN to a certificate of a domain?

### ISSUE THREAD

**Issue by tukusejssirs** [JonasAlfredsson/docker-nginx-certbot#250]
I want to add [Teleport](https://goteleport.com/) to Nginx. I have found [this guide](https://github.com/gravitational/teleport/discussions/26445), however, first issue I have encountered that I have no idea how to add a wildcard SAN to a certificate of a domain.

They suggest doing it using `certbot certonly -d teleport.example.com,*.teleport.example.com --dns-route53`. Now, that is clear to me, however, I am not sure how to do this in `docker-nginx-certbot`.

I have read [_Using a DNS-01 Authenticator for Specific Certificates Only_](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/certbot_authenticators.md#using-a-dns-01-authenticator-for-specific-certificates-only). It sounds it is what I am looking for, however, I am not sure how to create that DNS-01 authenticator. :thinking:

Some notes:

- we are self-hosting both `docker-nginx-certbot` and Teleport (along with some other services in Docker containers) on the same server;
- `docker-nginx-certbot` is running in a Docker container (obviously);
- Teleport is running directly on the host, not in a Docker container;
- I have managed to get `docker-nginx-certbot` working for other services.

Thank you for your help and for the image you have created! :pray:

**Comment by JonasAlfredsson** [comment]
Hi tukusejssirs,

In the section [above](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/certbot_authenticators.md#preparing-the-container-for-dns-01-challenges) there is a list of all supported DNS plugins with links to the cerbot documentation on how to configure them. 

Then you can probably just add this to your server block:
```
server_name example.com *.example.com 
```
and make sure the correct authenticator is mentioned in the certificate name path which you see in the first section you mentioned.

**Comment by JonasAlfredsson** [comment]
Did you manage to get it working?
