### ISSUE TITLE
map variable for server_name

### ISSUE THREAD

**Issue by Dunedubby** [JonasAlfredsson/docker-nginx-certbot#252]
I'm running into trouble using a `map` block to add some configurability to the `server_name`, something like:

```
map $host $server_host {
  default "$SERVER_HOST";
}
```

in a template file and then

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name $server_host;
    etc.
}
```

Does the code allow for this?

**Comment by JonasAlfredsson** [comment]
Hi  Dunedubby,

I am not exactly sure what you intend to do with this map, but you can probably make use of [overrides](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/advanced_usage.md#override-server_name).

**Comment by JonasAlfredsson** [comment]
Any more questions or can we close this issue?
