### ISSUE TITLE
how to use subdomain wildcard?

### ISSUE THREAD

**Issue by wade-liwei** [JonasAlfredsson/docker-nginx-certbot#259]
example.com

https://1.example.com
https://2.example.com
https://3.example.com

https://xxxxx.example.com

Access https://xxxxx.example.com with https.
How do I to replace xxxxx with any character?

**Comment by JonasAlfredsson** [comment]
Not exactly sure what you are trying to do, but in this example there are multiple servers configured and they share a single wildcard certificate: https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/examples/example_server_overrides.conf

Wildcard certs needs DNS authenticator: https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/certbot_authenticators.md

**Comment by wade-liwei** [comment]
@JonasAlfredsson 

server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl;
    listen [::]:443 ssl;

    # Domain names this server should respond to.
    server_name aonmesh.ai;
    server_name www.aonmesh.ai; # certbot_domain:*.aonmesh.ai

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/aonmesh.ai/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/aonmesh.ai/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/aonmesh.ai/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    return 200 'You have reached either yourdomain.org or www.yourdomain.org';
    add_header Content-Type text/plain;
}

nginx-1  | Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA. You may need to use an authenticator plugin that can do challenges over DNS.

**Comment by JonasAlfredsson** [comment]
Well, the error states that you have not configured an authenticator that is capable of DNS challenges, so you will need to do that before you can issue wildcard certificates.

**Comment by wade-liwei** [comment]
@JonasAlfredsson 

thank you.
