### ISSUE TITLE
How can i define a renew hook in docker-compose environment?

### ISSUE THREAD

**Issue by leonard0x00** [JonasAlfredsson/docker-nginx-certbot#266]
hello! im looking for use your docker image in my prod servers 

there's a way to define a post hook like 'nginx -s reload' in my docker-compose environment?

**Comment by JonasAlfredsson** [comment]
Hi, 

No there are currently no way of creating custom hooks after the renewal scripts run, but a reload of nginx is already done, see the last line in this file: https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src%2Fscripts%2Frun_certbot.sh

**Comment by leonard0x00** [comment]
cool! nice to know

so, if I let default auto renew script runs it will renew my certificates and my nginx will be reloaded?

im asking because i tried to force a renew with 'certbot renew --force-renewal' today and got no reload in nginx, but it worked after i edit the renew conf and added the post-hook instruct (and force a new renewal manually)

but was probably my mistake not checking all scripts in your repo, thanks a lot

**Comment by JonasAlfredsson** [comment]
Did you follow the instructions in the documentation? https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/advanced_usage.md#manualforce-renewal
