### ISSUE TITLE
How to add new config in running container?

### ISSUE THREAD

**Issue by CoWayger** [JonasAlfredsson/docker-nginx-certbot#271]
Hi, I migrated letsencrypt folder from bare metal certbot instalation and nginx configs. Now I need to add another config but can't find any info how. When I modify [this](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/examples/example_server.conf) example image refuses to HUP signal with error:
```
[emerg] 177#177: cannot load certificate "/etc/letsencrypt/live/mydomain/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/mydomain/fullchain.pem, r) error:10000080:BIO routines::no such file)
```

Should I run manually certbot in docker for first time? Should I shutdown whole image and it will generate certificate? (I think it refuses to start when nginx config is invalid)

Thank you.

**Comment by JonasAlfredsson** [comment]
Hi, 

How do you start the container (specifically which folders do you mount).

Can you provide all the configs you are using and perhaps the debug log from the container.

**Comment by JonasAlfredsson** [comment]
Any updates to this?
