### ISSUE TITLE
Expired certificate is not being replaced anymore

### ISSUE THREAD

**Issue by paradise** [JonasAlfredsson/docker-nginx-certbot#277]
Hi, I'm using this Docker a long time, I always use `image: jonasal/nginx-certbot:latest`.

From some time ago I have a problem, when my certificate is nearly expired or already expired, it is not being renewed.

When I restart docker, i see this lines

```
nginx  | 2024/07/30 19:59:27 [info] Requesting an ECDSA certificate for 'example.com' (http-01 through webroot)
nginx  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx  | Requesting a certificate for example.com and www.example.com
nginx  | Successfully received certificate.
nginx  | Certificate is saved at: /etc/letsencrypt/live/example.com-0002/fullchain.pem
nginx  | Key is saved at:         /etc/letsencrypt/live/example.com-0002/privkey.pem
nginx  | This certificate expires on 2024-10-28.
nginx  | These files will be updated when the certificate renews.
nginx  | NEXT STEPS:
nginx  | - The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
```

For some reeson, ceriticate folder is not the same as in my config:

```
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl;

    # Domain names this server should respond to.
    server_name example.com;
    server_name www.example.com;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

```

So I need to manually replace certificate folder in config to example.com-0002 to use new certificate. And again do it after 3 months.

What is wrong? I remember that before everything was ok and certificates where updating automatically.

**Comment by paradise** [comment]
I checked with the ` jonasal/nginx-certbot:5.2.1`, problem stil exists. Certificate is requsted but not replaced.

**Comment by JonasAlfredsson** [comment]
Hmm, that seems a little bit weird. Would it be possible for you to jump into the container and delete all the `/etc/letsencrypt/live/example.com*` and then do a full reload to see if it gets sorted out. I've not heard from anyone else that this is an issue.

**Comment by JonasAlfredsson** [comment]
Any updates to this?

**Comment by tukusejssirs** [comment]
@JonasAlfredsson, while I haven’t experienced this issue (all my certs are actually re-issued as expected), I stopped the my Docker container, backed `/etc/letsencrypt` up, removed `/etc/letsencrypt/live/*`, started up the container. Then, I get the following warning for every PEM file under `/etc/letsencrypt/live/$website/$filename.pem`.

```bash
Could not find non-zero size chain file '/etc/letsencrypt/live/$website/$filename.pem' in '/etc/nginx/conf.d/$website.conf.nokey'
```

And no website is accessible (`Secure Connection Failed`).

**Comment by JonasAlfredsson** [comment]
I would probably remove everything in `/etc/letsencrypt/`, an not just in `live`, to trigger a reset of certbot. 

I would probably need all of the logs to tell you what goes wrong in your current test.

**Comment by JonasAlfredsson** [comment]
Poking this again :)

**Comment by Grimeh** [comment]
Just run into this on 6.0.0. Luckily we caught it relatively quickly.

Looks like certbot will save new certificates in `/etc/letsencrypt/live/example-XXXX`, incrementing the number each time. We were up to `0022`, for example.

The contents of the new live folder are sym-linked to the matching archive folder, if that's of interest (eg. `../../archive/example-0022/cert.pem`).

I can see from the modification times that the contents of the `/etc/letsencrypt/live/example` folder weren't ever updated, timestamp is about 3 months ago.

Is this a certbot or container issue?
