### ISSUE TITLE
Consider updating nginx to 1.27.1 for critical vulnerabilities.

### ISSUE THREAD

**Issue by ivanvaccari** [JonasAlfredsson/docker-nginx-certbot#290]
The latest image of docker-nginx-certbot is based on nginx:127.0, which, accordingly to docker scout, is affected by 4 critical vulnerabilities:

![image](https://github.com/user-attachments/assets/bdd929b1-0cda-412e-bca8-4e3eada24b3c)
source: https://hub.docker.com/layers/library/nginx/1.27.0/images/sha256-a3ab061d6909191271bcf24b9ab6eee9e8fc5f2fbf1525c5bd84d21f27a9d708?context=explore

Please consider updating nginx to 1.27.1, which fixes these critical vulnerabilities:

![image](https://github.com/user-attachments/assets/91fcc55e-c7c0-4c32-833a-ddc9c16a04c9)

source: https://hub.docker.com/layers/library/nginx/1.27.1/images/sha256-10b61fc3d8262c8bf44c89aef3d81202ce12b8cba12fff2e32ca5978a2d88c2b?context=explore

Thanks!

**Comment by JonasAlfredsson** [comment]
Sorry for late reply, but usually dependabot fixes all the updates but for some reason it did not produce a commit for 1.27.1 and jumped directly to 1.27.2. 

Nevertheless, this is now built and uploaded.
