### ISSUE TITLE
Consider adding Jinja templates

### ISSUE THREAD

**Issue by dtcooper** [JonasAlfredsson/docker-nginx-certbot#294]
Would you consider adding [Jinja](https://jinja.palletsprojects.com/) templates to the image? I find them **super** useful in my projects.

I've created [`dtcooper/docker-nginx-certbot-jinja`](https://github.com/dtcooper/docker-nginx-certbot-jinja/) which does this (see project's README). I was thinking, since adding the [`jinjanate`](https://github.com/kpfleming/jinjanator) command is really trivial (we already have Python + pip in the container images), I'm wondering if we might add my Jinja template processing code here.

They could be applied pretty easily, ie with a script at `/docker-entrypoint.d/25-jinja-on-templates.sh` as follows:

```bash
#!/bin/bash

set -e

ME=$(basename "$0")

entrypoint_log() {
    if [ -z "${NGINX_ENTRYPOINT_QUIET_LOGS:-}" ]; then
        echo "$@"
    fi
}

# Adapted from 20-envsubst-on-templates.sh
auto_jinja() {
  local template_dir="${NGINX_JINJA_TEMPLATE_DIR:-/etc/nginx/templates}"
  local suffix="${NGINX_JINJA_TEMPLATE_SUFFIX:-.jinja}"
  local output_dir="${NGINX_JINJA_OUTPUT_DIR:-/etc/nginx/conf.d}"

  local template relative_path output_path subdir
  [ -d "$template_dir" ] || return 0
  if [ ! -w "$output_dir" ]; then
    entrypoint_log "$ME: ERROR: $template_dir exists, but $output_dir is not writable"
    return 0
  fi
  find "$template_dir" -follow -type f -name "*$suffix" -print | while read -r template; do
    relative_path="${template#$template_dir/}"
    output_path="$output_dir/${relative_path%$suffix}"
    subdir=$(dirname "$relative_path")
    mkdir -p "$output_dir/$subdir"
    entrypoint_log "$ME: Running jinjanate (jinja template) on $template to $output_path"
    jinjanate --quiet --undefined --output-file "$output_path" "$template"
  done
}

auto_jinja
```

If you like the idea, I can prepare a merge request with tests and can add information about it to the documentation.

Cheers,

David

**Comment by JonasAlfredsson** [comment]
Hi dtcooper,

Thanks for the suggestion, but I feel this is a little bit too much feature creep than I feel comfortable maintaining. 

I do agree that jinja templating is powerful and useful, I just don't see it be this container's job to assemble complicated configuration files (i.e. it makes runtime changes to files present on disk). To me this belongs to an external deployment step, most likely through Ansible, where unique configurations are assembled on a per host basis or similar, so it is much easier for one to debug the deployment when something goes wrong.

May I inquire more how you are using this in your workflow?

**Comment by dtcooper** [comment]
Simplest use case would be conditionals based on environment variables (ie for a development vs. production environment). But anything more powerful than `envsubst` variable substituation.

Here [are](https://github.com/dtcooper/tomato/blob/main/server/nginx.conf.jinja) [some](https://github.com/dtcooper/crazyarms/blob/master/nginx/image/etc/nginx/templates/default.conf.j2) [examples](https://github.com/dtcooper/radio-calls/blob/main/nginx.conf.jinja) of how I've used Jinja-based templates for Nginx config in my projects.

**Comment by JonasAlfredsson** [comment]
Thank you for the examples, but I would say that this is out of scope of *this* container, and I feel like adding support for this would increase complexity and possibly cause some confusion for those less technically experienced. 

However, I see you have already set up automatic build and push of your image, and you can probably just add Dependabot as well since I am quite sure it picks up when a new image is uploaded from here. So then you can just merge those changes and fully automate a release of your custom image.
