### ISSUE TITLE
too many certificates (5) already issued for this exact set of domains in the last 168h0m0s

### ISSUE THREAD

**Issue by Atkion** [JonasAlfredsson/docker-nginx-certbot#295]
Hello, 

I'm trying to request certificates for 9 subdomains total. 
I'm fairly sure I have it configured correctly, because the first 5 requests work just fine, returning a `Successfully received certificate.`

However, after the 5th request, every subsequent request gets hit with `acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: too many certificates (5) already issued for this exact set of domains in the last 168h0m0s, retry after 2024-10-20 03:25:33 UTC: see https://letsencrypt.org/docs/duplicate-certificate-limit/`.

That left me with 5 subdomains with working certs, and 4 without.
Is there a way I can work around this limitation, like splitting up the requests into groups of 5 or fewer? 

For now, I have been able to manually enter the certbot commands for the remaining 4 subdomains, so everything is working. Something like this:
```certbot certonly --agree-tos --keep -n --text --preferred-challenges http-01 --authenticator webroot --webroot-path=/var/www/letsencrypt --email <email> --server https://acme-v02.api.letsencrypt.org/directory --rsa-key-size 2048 --elliptic-curve secp256r1 --key-type ecdsa --cert-name '<subdomain>' -d '<subdomain>' --debug --force-renewal```
However, I worry that they will not automatically renew properly, and will hit this issue again when the next cycle comes around. 

Here is my docker run command (being executed through the Unraid GUI).
```
docker run
  -d
  --name='nginx-certbot'
  --net='bridge'
  --pids-limit 2048
  --privileged=true
  -e TZ="<tz>"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="<hostname>"
  -e HOST_CONTAINERNAME="nginx-certbot"
  -e 'CERTBOT_EMAIL'='<email>'
  -e 'STAGING'='0'
  -l net.unraid.docker.managed=dockerman
  -p '12344:443/tcp'
  -p '12345:80/tcp'
  -v '/mnt/user/Docker/nginx/letsencrypt/':'/etc/letsencrypt':'rw'
  -v '/mnt/user/Docker/nginx/config/':'/etc/nginx/user_conf.d':'ro' 'jonasal/nginx-certbot:latest'
  ```
  
I'll be happy to include my nginx config as well if you think it's relevant, but given that it's working when certbot is run manually, I think it's probably fine.

Thanks for your help!

**Comment by JonasAlfredsson** [comment]
Hi Atkion,

I have a hunch of what might be the problem, but I will need to see the configuration files as well in order to give you any advise on this.

**Comment by Atkion** [comment]
Alright, here you go. I'm sure this will make it painfully obvious how clumsily I've thrown all this together, but ah well.
I've tried to redact it somewhat while hopefully preserving any errors I've made. Cheers!
```
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name domain.com;
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
    location / {
        return 302 <redirect>;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain1>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain1>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain1>.domain.com/privkey.pem;
    location / {
        proxy_pass <internal_location>;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain2>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain2>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain2>.domain.com/privkey.pem;

location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass <internal_location>;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain3>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain3>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain3>.domain.com/privkey.pem;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    location / {
        proxy_pass <internal_location>;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain4>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain4>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain4>.domain.com/privkey.pem;
    location / {
        proxy_pass <internal_location>;
    }
}
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name <subdomain5>.domain.com;
  ssl_certificate     /etc/letsencrypt/live/<subdomain5>.domain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/<subdomain5>.domain.com/privkey.pem;

  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $host;
    proxy_pass         <internal_location>;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain6>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain6>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain6>.domain.com/privkey.pem;
    location / {
        proxy_pass <internal_location>;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain7>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain7>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain7>.domain.com/privkey.pem;
    location / {
        proxy_pass <internal_location>;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl http2;
    server_name <subdomain8>.domain.com;
    ssl_certificate /etc/letsencrypt/live/<subdomain8>.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<subdomain8>.domain.com/privkey.pem;
    client_max_body_size 0;
    location / {
        proxy_pass <internal_location>;
    }
}
```

**Comment by JonasAlfredsson** [comment]
Ah, it was as I suspected. 

I am just curious regarding my documentation, would you have been able to figure out the issue if I just told you to read [this section](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#how-the-script-add-domain-names-to-certificate-requests) of the documentation (because it is not the first time this has happened :) )

<details>
  <summary>The answer if you just want it directly </summary>
  

How the certificate request script functions is that it takes all found `server_names` in the file, and adds them to *all* `ssl_certificate_key`  files found in the same file. 

So in your case you get 8 separate certificate files (8 requests), where every certificate contains all subdomains you have listed. This leads a lot of redundant certificates as you can imagine. 

The solution to this is to either use the same `ssl_certificate_key` for all server blocks, or split each server block into its own file. 
</details>

**Comment by JonasAlfredsson** [comment]
Also [Configuration inheritence](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/nginx_tips.md#configuration-inheritance) might also be of interest to you if you want to reduce the amount of header settings.

**Comment by Atkion** [comment]
Ah, I see. That makes a lot of sense. 

Reading through that documentation now, I definitely see what you mean, and I'll tweak my config so it's using the same cert for every subdomain. 

I think the gap here wasn't in your documentation, but in my understanding of how certs work in general. I knew wildcard certs exist and can be used for multiple subdomains, but I did not realize you could just add multiple subdomains to a normal cert and use the same one across the board. I imagine that could go for other people as well, stumbling through their setup via trial and error like I am. 

Thank you for your extremely helpful and considerate response - I'm aware that I'm very ignorant in this area, and I know how obnoxious it can be explaining the same things ad nauseam. Cheers!

**Comment by JonasAlfredsson** [comment]
No worries at all, I am just glad I could help and that you find the project useful, it was a very easy fix and you learned something today :)

mAlso, More info about how you can enable star certificates can be found [here](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/certbot_authenticators.md), it is definitely a more advanced setup but if you want to continue your journey it is probably the next step ;)
