### ISSUE TITLE
Provide an Alpine build for this image

### ISSUE THREAD

**Issue by JonasAlfredsson** [JonasAlfredsson/docker-nginx-certbot#42]
There was one user that wondered why I did not use Alpine for this image, and I answered them in the tread [over here](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/35). However, I started looking into this and I think it shouldn't be too difficult to build an Alpine image as well.

**Comment by JonasAlfredsson** [comment]
Of course I spoke too soon, and it looks like I have run into a bug in Bash 5.1.0 that breaks my SIGHUP trap. 
I have created a minimalistic reproducer over [here](https://github.com/JonasAlfredsson/bash_fail-to-wait), and it looks like I will have to file some kind of bug report after this...

**Comment by JonasAlfredsson** [comment]
Good news seems to be that the [QEMU 32-bit](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/30) bug is not present in the cargo package in Alpine. This probably means that this will be fixed in a later image of Debian as well.

**Comment by JonasAlfredsson** [comment]
This now seems to work, but this has made a lot of different tag combinations possible. Check out the table to get a better understanding of which Docker tags that can be specified :)
https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/dockerhub_tags.md

**Comment by tudddorrr** [comment]
@JonasAlfredsson working perfectly for me, thanks!

**Comment by JonasAlfredsson** [comment]
Excellent!
I will then close this issue, but please let me know if anything goes awry in the future :)

**Comment by dtcooper** [comment]
This bug created an issue with dependency versions when apk is used on derivatives of the container.

The fix is submitted as PR #117
