### ISSUE TITLE
Support ECDSA keys

### ISSUE THREAD

**Issue by JonasAlfredsson** [JonasAlfredsson/docker-nginx-certbot#43]
Certbot has the option to request [ECDSA keys instead of RSA](https://certbot.eff.org/docs/using.html#using-ecdsa-keys), and I think it would be neat if we added an option for users to define an environment variable in order to use this feature. 

Perhaps something like this:

```
ECDSA-CURVE=secp256r1
```

and this will add `--key-type ecdsa --elliptic-curve secp256r1` to the config parameters in to the certificate request.

**Comment by JonasAlfredsson** [comment]
https://community.letsencrypt.org/t/sha256withrsa-instead-ecdsa-with-sha256-with-certbot/145358

https://medium.com/hackernoon/rsa-and-ecdsa-hybrid-nginx-setup-with-letsencrypt-certificates-ee422695d7d3

https://cromwell-intl.com/open-source/google-freebsd-tls/tls-certificate.html

**Comment by JonasAlfredsson** [comment]
Hey @odin568, 

You are pretty active here, so I was wondering if I could ask you to test out the changes I have made over in the [dev](https://github.com/JonasAlfredsson/docker-nginx-certbot/tree/dev) branch?
I have added quite a bit of code that should be able to request ECDSA certificates both based on an environment variable, as well as the name of the certificate. 
I would love your feedback on both the functionality and the documentaion if you have some time to spare :)

This is also possible to pull by adding the `:dev` tag to the image.

**Comment by odin568** [comment]
Hey @JonasAlfredsson 
yes sure, no problem. Unfortunately I am off the next week for vacation. At latest afterwards will give it a try! Well read a bit about ECDSA certificates, also quite new to me.
Thank you!

**Comment by JonasAlfredsson** [comment]
Great! No worries, there is no rush, just wanted someone else give it a read so there are no obvious mistakes :) 
I have tried to add some extra links to external sources that explain what ECDSA is, so perhaps you could rate them as well ;)

**Comment by odin568** [comment]
Hi @JonasAlfredsson 
sorry for late notice. Just gave it a quick try with `USE_ECDSA=1` and renewed certificate. Works like a charm and got new elliptic curve certificate and seems to work for my use case!
Also had a rouch look at the documentation and looks fine for me!
Thanks and regards!

**Comment by JonasAlfredsson** [comment]
Excellent! 
I have just pushed these changes to the master branch, so well have to see if anyone runs into some bug down the line. I think it should be pretty solid, but you never know. :)
Thank you very much for helping me out with this, and I hope it will work well for you in the future as well!
