### ISSUE TITLE
Reason for the :81 proxy?

### ISSUE THREAD

**Issue by klodoma** [JonasAlfredsson/docker-nginx-certbot#53]
In `https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/nginx_conf.d/certbot.conf` there is the :81 proxy created. 

The same functionality can be achieved by the `redirector.conf`

```
    location ^~ /.well-known/acme-challenge {
        default_type text/plain;
        root /var/www/letsencrypt;
    }
```

I am just questioning the reason for the proxy.

**Comment by JonasAlfredsson** [comment]
Hi klodoma, 

The reason i probably not that clear anymore, and you are completely right that it could be achieved by only the redirector. Previously the `certbot.conf` had its own logging statements as well, which made a little bit more justified to be standalone, but as of now it is more a legacy. I also think that (a long time ago) I had some thought about that users might want to be able to have their own `certbot.conf`, but that doesn't really make sense right now either. 

I am working on some other features right now, but this can perhaps be compacted in a future update :)

**Comment by klodoma** [comment]
@JonasAlfredsson All right, I think it makes it clear then. Thank you for the answer.
