### ISSUE TITLE
Error during startup of my Image

### ISSUE THREAD

**Issue by Mellywins** [JonasAlfredsson/docker-nginx-certbot#59]
Hello!
After checking up my container logs, i have run into the following errors:
`Could not find keyfile file '/etc/letsencrypt/live/legalisation/privkey.pem;' in '/etc/nginx/conf.d/nginx.conf'`
`Could not find keyfile file '/etc/letsencrypt/live/legalisation/privkey.pem' in '/etc/nginx/conf.d/nginx.conf'`
This seems to be normal since the container just started and it doesn't have the files yet.
But what happens later is quite bothersome.
`Important file(s) for '/etc/nginx/conf.d/nginx.conf' are missing, disabling...`
Then i get another notice that nginx could not find key files then certbot goes to sleep. Any insights on this issue?

**Comment by Mellywins** [comment]
I checked the logs file of letsencrypt and the issue was having a default_server in the server name inside nginx.conf.

**Comment by JonasAlfredsson** [comment]
Hi Mellywins,

Glad to hear that you found the solution yourself, however, would you like to post the configuration that caused issues so future people may search for this and see the solution? :)

**Comment by Mellywins** [comment]
Hi Jonas,
Of course, I posted the old conf file and closed my issue as the solution you provided in your reply works.
Thank you for your thorough solution as it saved me multiple hours of head banging.
Cheers!

**Comment by JonasAlfredsson** [comment]
Thank you and no worries, glad I could help :)
