### ISSUE TITLE
Split config file

### ISSUE THREAD

**Issue by theautomation** [JonasAlfredsson/docker-nginx-certbot#62]
Hi, i have multiple services that is availeble on the same domain so i put all theses server blocks in one file as discripted in the good to know readme. There is no way to split the config in files voor each server block?

_The limitation is that you should write all your server blocks that use the same "test-name" certificate in the same file._

**Comment by JonasAlfredsson** [comment]
Hi theautomation,

Would you mind posting an example of what you have today, and describe how you would like to have it split, in order to make it a little bit easier for me to help you :)

**Comment by theautomation** [comment]
Hi JonasAlfredsson, i have got these two server blocks in one file called mydomain.config in the conf.d directory:

`# 1
upstream prd-home-assistant {
	server docker.stam.lan:8123;
}

server {
    listen                      443 ssl;
    server_name                 homeassistant.theautomation.nl;
    server_tokens               off;
    
    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass              http://prd-home-assistant;
        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_set_header        X-Forwarded-Host    $server_name;
        proxy_set_header        Upgrade             $http_upgrade;
        proxy_set_header        Connection          "Upgrade";
    }
}

# 2
upstream prd-drone {
	server prd-drone-server:80;
}

server {
    listen                      443 ssl;
    server_name                 drone.theautomation.nl;
    server_tokens               off;

    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass                  http://prd-drone;
        proxy_set_header            Host                $http_host;
        proxy_set_header            X-Real-IP           $remote_addr;
        proxy_set_header            X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header            X-Forwarded-Proto   $scheme;
        proxy_set_header            X-Forwarded-Host    $server_name;
        proxy_redirect              off;
        proxy_http_version          1.1;
        proxy_buffering             off;
        chunked_transfer_encoding   off;
    }
}`

What i want is split these two in two seperate files to get:

``# 1
upstream prd-home-assistant {
	server docker.stam.lan:8123;
}

server {
    listen                      443 ssl;
    server_name                 homeassistant.theautomation.nl;
    server_tokens               off;
    
    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass              http://prd-home-assistant;
        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_set_header        X-Forwarded-Host    $server_name;
        proxy_set_header        Upgrade             $http_upgrade;
        proxy_set_header        Connection          "Upgrade";
    }
}``

And

`# 2
upstream prd-drone {
	server prd-drone-server:80;
}

server {
    listen                      443 ssl;
    server_name                 drone.theautomation.nl;
    server_tokens               off;

    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass                  http://prd-drone;
        proxy_set_header            Host                $http_host;
        proxy_set_header            X-Real-IP           $remote_addr;
        proxy_set_header            X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header            X-Forwarded-Proto   $scheme;
        proxy_set_header            X-Forwarded-Host    $server_name;
        proxy_redirect              off;
        proxy_http_version          1.1;
        proxy_buffering             off;
        chunked_transfer_encoding   off;
    }
}`

**Comment by theautomation** [comment]
Hi JonasAlfredsson, i have got these two server blocks in one file called mydomain.config in the conf.d directory:

```
# Home Assistant
upstream prd-home-assistant {
	server docker.stam.lan:8123;
}

server {
    listen                      443 ssl;
    server_name                 homeassistant.theautomation.nl;
    server_tokens               off;
    
    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";
    location / {
        proxy_pass              http://prd-home-assistant;
        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_set_header        X-Forwarded-Host    $server_name;
        proxy_set_header        Upgrade             $http_upgrade;
        proxy_set_header        Connection          "Upgrade";
    }
}

# Drone
upstream prd-drone {
	server prd-drone-server:80;
}

server {
    listen                      443 ssl;
    server_name                 drone.theautomation.nl;
    server_tokens               off;

    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass                  http://prd-drone;
        proxy_set_header            Host                $http_host;
        proxy_set_header            X-Real-IP           $remote_addr;
        proxy_set_header            X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header            X-Forwarded-Proto   $scheme;
        proxy_set_header            X-Forwarded-Host    $server_name;
        proxy_redirect              off;
        proxy_http_version          1.1;
        proxy_buffering             off;
        chunked_transfer_encoding   off;
    }
}
```
What i want is to seperate the two blocks in its own file, it works for NGINX but i only get a certificate for the first config file found from a-z. 
Example: 

homeassistant.config 
```
# Home Assistant
upstream prd-home-assistant {
	server docker.stam.lan:8123;
}

server {
    listen                      443 ssl;
    server_name                 homeassistant.theautomation.nl;
    server_tokens               off;
    
    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";
    location / {
        proxy_pass              http://prd-home-assistant;
        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_set_header        X-Forwarded-Host    $server_name;
        proxy_set_header        Upgrade             $http_upgrade;
        proxy_set_header        Connection          "Upgrade";
    }
}
```

drone.config
```
# Drone
upstream prd-drone {
	server prd-drone-server:80;
}

server {
    listen                      443 ssl;
    server_name                 drone.theautomation.nl;
    server_tokens               off;

    ssl_certificate             /etc/letsencrypt/live/theautomation.nl/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/theautomation.nl/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/theautomation.nl/chain.pem;
    ssl_dhparam                 /etc/letsencrypt/dhparams/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED";

    location / {
        proxy_pass                  http://prd-drone;
        proxy_set_header            Host                $http_host;
        proxy_set_header            X-Real-IP           $remote_addr;
        proxy_set_header            X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header            X-Forwarded-Proto   $scheme;
        proxy_set_header            X-Forwarded-Host    $server_name;
        proxy_redirect              off;
        proxy_http_version          1.1;
        proxy_buffering             off;
        chunked_transfer_encoding   off;
    }
}
```

**Comment by JonasAlfredsson** [comment]
Thanks for the config files, it makes it much clearer what you are trying to do.
So the reason for why you only get one valid certificate when they are split up is because of this:

- The renewal script finds `drone.config`
- Certbot starts a renewal request for `drone.theautomation.nl`, since that is the only `server_name` found.
- The result is written to `theautomation.nl/fullchain.pem`
- The renewal script finds `homeassistant.config`
- Certbot starts a renewal request for `homeassistant.theautomation.nl`, since that is the only `server_name` found.
- The result is written to `theautomation.nl/fullchain.pem` **Here you overwrite the previous one**.

The solution is either to keep them in the same file, since then all `server_names` will be part of the same certificate, or you can just make the path name unique in the two different files. For example, you can have it named like this `homeassistant.theautomation.nl/fullchain.pem` in the first config, and then `drone.theautomation.nl/fullchain.pem` in the second. Or you can just make them `homeassistant/fullchain.pem` and  `drone/fullchain.pem`, the only importance is that they are unique.

**Comment by JonasAlfredsson** [comment]
Did it work for you?

**Comment by theautomation** [comment]
Sorry I haven't had time to try it yet. I'll let you know as soon as it works or not

**Comment by theautomation** [comment]
Hi JonasAlfredsson, sorry for the long wait. I can confirm that creating a unique path works and now get a certificate for each subdomain, so I can split the config this way.

**Comment by JonasAlfredsson** [comment]
Excellent!
I will close this issue for now then, but please don't hesitate to open an new one in case you run into any more trouble :)
