### ISSUE TITLE
Example docker-compose.yml didn't work due to both environment and env_file being specified

### ISSUE THREAD

**Issue by dajtxx** [JonasAlfredsson/docker-nginx-certbot#68]
The env var settings in nginx-certbot.env were not being used.

I read the docker-compose docs and they say that env vars declared in the environment section override those read from a file in the env_file section, even if they are not set in the compose file or in the parent process env.

When I removed the environment section from the compose file the values were read from the nginx-certbot.env file.

The example file needs a comment to explain only one or the other should be used.

**Comment by JonasAlfredsson** [comment]
Hi 

I added this comment, do you think this will suffice or should we add something more?
https://github.com/JonasAlfredsson/docker-nginx-certbot/commit/e9579e02857054e27b6394951084837063c1b75b

**Comment by JonasAlfredsson** [comment]
I changed my mind a little bit about the comment. To reduce the confusion we can perhaps remove all of the variables from the `.yaml` file, and add a note that the `env_file` is not obligatory to have: https://github.com/JonasAlfredsson/docker-nginx-certbot/commit/ba70dd9adcda9ef7de157cfb841f2f3056de0948

**Comment by JonasAlfredsson** [comment]
I changed the examples a bit to make it more difficult to run into the issue you experienced. Hope this will suffice :)
